/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

/**
 * @description Default Response
 */
export const sendMagicLink204Schema = z.any()

export const sendMagicLinkMutationRequestSchema = z.object({
  email: z.string().email(),
})

export const sendMagicLinkMutationResponseSchema = z.lazy(() => sendMagicLink204Schema)