/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type CreateUser201 = any;

export type CreateUserMutationRequest = {
  /**
   * @type string
   */
  name: string;
  /**
   * @type string, email
   */
  email: string;
  /**
   * @type string
   */
  password: string;
};

export type CreateUserMutationResponse = CreateUser201;

export type CreateUserMutation = {
  Response: CreateUser201;
  Request: CreateUserMutationRequest;
  Errors: any;
};
