/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Default Response
 */
export type SendMagicLink204 = any

export type SendMagicLinkMutationRequest = {
  /**
   * @type string, email
   */
  email: string
}

export type SendMagicLinkMutationResponse = SendMagicLink204

export type SendMagicLinkMutation = {
  Response: SendMagicLink204
  Request: SendMagicLinkMutationRequest
  Errors: any
}